name: All Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: chmod +x gradlew
        run: chmod +x gradlew
      - name: git submodule init
        run: git submodule init
      - name: git submodule update --remote
        run: git submodule update --remote
      - name: Init gradle project
        run: ./gradlew clean
      - name: Build all
        run: ./gradlew assemble
      - name: All Tests
        run: ./gradlew check
