name: mirai-core Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: chmod +x gradlew
        run: chmod +x gradlew
      - name: Init gradle project
        run: ./gradlew clean
      - name: Build mirai-core series
        run: ./gradlew assemble
      - name: mirai-core Tests
        run: ./gradlew check
